services:
  mkapi:
    build: .
    container_name: mkapi
    ports:
      - "${HOST_PORT:-8000}:8000"
    environment:
      APP_ENV: ${APP_ENV}

      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_TRACES_EXPORTER: ${OTEL_TRACES_EXPORTER}
      OTEL_METRICS_EXPORTER: ${OTEL_METRICS_EXPORTER}
      OTEL_LOGS_EXPORTER: ${OTEL_LOGS_EXPORTER}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: ${OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED}
      OTEL_PYTHON_LOG_LEVEL: ${OTEL_PYTHON_LOG_LEVEL}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    depends_on:
      - postgres
      - otel-collector

    command: >
      poetry run opentelemetry-instrument
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --app-dir src

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      APP_ENV: ${APP_ENV}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
    ports:
      - "4318:4318"
      - "4317:4317"

  postgres:
    image: postgres:16
    container_name: mkapi-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - mkapi-postgres-data:/var/lib/postgresql/data

volumes:
  mkapi-postgres-data:
