from enum import Enum


class ClientErrorType(Enum):
    CLIENT_ALREADY_EXISTS = "CLIENT_ALREADY_EXISTS"
    CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND"


class AnalysisMethodErrorType(Enum):
    ANALYSIS_METHOD_ALREADY_EXISTS = "ANALYSIS_METHOD_ALREADY_EXISTS"
    ANALYSIS_METHOD_NOT_FOUND = "ANALYSIS_METHOD_NOT_FOUND"


class TestTypeErrorType(Enum):
    TEST_TYPE_ALREADY_EXISTS = "TEST_TYPE_ALREADY_EXISTS"
    TEST_TYPE_NOT_FOUND = "TEST_TYPE_NOT_FOUND"


class AnalyteErrorType(Enum):
    ANALYTE_ALREADY_EXISTS = "ANALYTE_ALREADY_EXISTS"
    ANALYTE_NOT_FOUND = "ANALYTE_NOT_FOUND"


class DomainErrorType(Enum):
    DOMAIN_ERROR = "DOMAIN_ERROR"


class UnexpectedErrorType(Enum):
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
